services:
    # Controllers
    MakG\UserBundle\Controller\RegistrationController:
        class: MakG\UserBundle\Controller\RegistrationController
        public: true
        calls:
            -   method: setContainer
                arguments: ['@service_container']
        arguments:
            - '@MakG\UserBundle\Manager\UserManagerInterface'
            - '@event_dispatcher'
            - ~

    MakG\UserBundle\Controller\ResettingController:
        class: MakG\UserBundle\Controller\ResettingController
        public: true
        calls:
            -   method: setContainer
                arguments: ['@service_container']
        arguments:
            - '@MakG\UserBundle\Manager\UserManagerInterface'
            - '@event_dispatcher'
            - '@translator'
            - 0
            - 0
            - ~
            - ~

    MakG\UserBundle\Controller\SecurityController:
        class: MakG\UserBundle\Controller\SecurityController
        public: true
        calls:
            -   method: setContainer
                arguments: ['@service_container']
        arguments:
            - ~
            - '@security.authentication_utils'

    # Services
    makg_user.avatar_generator.identicon:
        class: MakG\UserBundle\AvatarGenerator\IdenticonGenerator

    makg_user.user_manager:
        class: MakG\UserBundle\Manager\UserManager
        public: true
        arguments:
            - '%makg_user.user_class%'
            - '@doctrine.orm.entity_manager'
            - '@security.password_encoder'

    makg_user.user_manipulator:
        class: MakG\UserBundle\Manager\UserManipulator
        arguments:
            - '@MakG\UserBundle\Manager\UserManagerInterface'
            - '@MakG\UserBundle\AvatarGenerator\AvatarGeneratorInterface'
            - '@filesystem'
            - '@security.csrf.token_generator'

    makg_user.noop_mailer:
        class: MakG\UserBundle\Mailer\NoopMailer

    makg_user.twig_swift_mailer:
        class: MakG\UserBundle\Mailer\TwigSwiftMailer
        arguments:
            - '@mailer'
            - '@twig'
            - '%makg_user.email_sender%'
            - '@router'

    makg_user.twig_symfony_mailer:
        class: MakG\UserBundle\Mailer\TwigSymfonyMailer
        arguments:
            - '@mailer'
            - '@twig'
            - '@router'
            - '%makg_user.email_sender%'

    makg_user.login_manager:
        class: MakG\UserBundle\Security\LoginManager
        arguments:
            - '@security.token_storage'
            - ~

    makg_user.user_checker:
        class: MakG\UserBundle\Security\UserChecker

    makg_user.user_provider:
        class: MakG\UserBundle\Security\UserProvider
        arguments:
            - '@MakG\UserBundle\Manager\UserManagerInterface'

    # Event Subscribers
    makg_user.listener.generate_confirmation_token:
        class: MakG\UserBundle\EventListener\GenerateConfirmationToken
        arguments:
            - '@security.csrf.token_generator'
        tags: [kernel.event_subscriber]

    makg_user.listener.send_emails:
        class: MakG\UserBundle\EventListener\SendEmails
        arguments:
            - '@MakG\UserBundle\Mailer\MailerInterface'
            - '@logger'
        tags: [kernel.event_subscriber]

    # Commands
    makg_user.command.create_user:
        class: MakG\UserBundle\Command\CreateUserCommand
        arguments:
            - '@MakG\UserBundle\Manager\UserManagerInterface'
            - '@MakG\UserBundle\Manager\UserManipulatorInterface'
            - '@MakG\UserBundle\Mailer\MailerInterface'
            - '@validator'
        tags: [console.command]

    makg_user.command.update_user:
        class: MakG\UserBundle\Command\UpdateUserCommand
        arguments:
            - '@MakG\UserBundle\Manager\UserManagerInterface'
            - '@MakG\UserBundle\Manager\UserManipulatorInterface'
            - '@makg_user.user_provider'
        tags: [console.command]

    makg_user.command.change_password:
        class: MakG\UserBundle\Command\ChangePasswordCommand
        arguments:
            - '@MakG\UserBundle\Manager\UserManagerInterface'
            - '@MakG\UserBundle\Manager\UserManipulatorInterface'
            - '@makg_user.user_provider'
        tags: [console.command]

    makg_user.command.roles:
        class: MakG\UserBundle\Command\RolesCommand
        arguments:
            - '@MakG\UserBundle\Manager\UserManagerInterface'
            - '@MakG\UserBundle\Manager\UserManipulatorInterface'
            - '@makg_user.user_provider'
        tags: [console.command]

    makg_user.command.promote:
        class: MakG\UserBundle\Command\PromoteCommand
        tags: [console.command]

    makg_user.command.demote:
        class: MakG\UserBundle\Command\DemoteCommand
        tags: [console.command]

    # Aliases
    MakG\UserBundle\AvatarGenerator\AvatarGeneratorInterface:
        alias: 'makg_user.avatar_generator.identicon'

    MakG\UserBundle\Mailer\MailerInterface:
        alias: 'makg_user.twig_symfony_mailer'

    MakG\UserBundle\Manager\UserManagerInterface:
        alias: 'makg_user.user_manager'

    MakG\UserBundle\Manager\UserManipulatorInterface:
        alias: 'makg_user.user_manipulator'

    MakG\UserBundle\Security\UserChecker:
        alias: 'makg_user.user_checker'

    MakG\UserBundle\Security\LoginManagerInterface:
        alias: 'makg_user.login_manager'
