services:
    # Controllers
    MakG\UserBundle\Controller\RegistrationController:
        class: MakG\UserBundle\Controller\RegistrationController
        public: true
        arguments:
            - '@MakG\UserBundle\Manager\UserManagerInterface'
            - '@event_dispatcher'
            - ~

    MakG\UserBundle\Controller\ResettingController:
        class: MakG\UserBundle\Controller\ResettingController
        public: true
        arguments:
            - '@MakG\UserBundle\Manager\UserManagerInterface'
            - '@event_dispatcher'
            - '@translator'
            - 0
            - 0
            - ~
            - ~

    MakG\UserBundle\Controller\SecurityController:
        class: MakG\UserBundle\Controller\SecurityController
        public: true
        arguments:
            - ~

    # Services
    makg_user.user_manager:
        class: MakG\UserBundle\Manager\UserManager
        arguments:
            - ~
            - '@doctrine.orm.entity_manager'
            - '@security.password_encoder'

    makg_user.mailer:
        class: MakG\UserBundle\Mailer\TwigSwiftMailer
        arguments:
            - '@mailer'
            - '@twig'

    makg_user.login_manager:
        class: MakG\UserBundle\Security\LoginManager
        arguments:
            - '@security.token_storage'
            - ~

    # Event Subscribers
    makg_user.listener.generate_confirmation_token:
        class: MakG\UserBundle\EventListener\GenerateConfirmationToken
        arguments:
            - '@security.token_generator'

    makg_user.listener.send_emails:
        class: MakG\UserBundle\EventListener\SendEmails
        arguments:
            - '@MakG\UserBundle\Mailer\MailerInterface'
            - '@logger'

    # Aliases
    MakG\UserBundle\Mailer\MailerInterface:
        alias: 'makg_user.mailer'

    MakG\UserBundle\Manager\UserManagerInterface:
        alias: 'makg_user.user_manager'
    
