services:
    # Controllers
    MakG\UserBundle\Controller\RegistrationController:
        class: MakG\UserBundle\Controller\RegistrationController
        public: true
        arguments:
            - '@MakG\UserBundle\Manager\UserManagerInterface'
            - '@event_dispatcher'
            - ~

    MakG\UserBundle\Controller\ResettingController:
        class: MakG\UserBundle\Controller\ResettingController
        public: true
        arguments:
            - '@MakG\UserBundle\Manager\UserManagerInterface'
            - '@event_dispatcher'
            - '@translator'
            - 0
            - 0
            - ~
            - ~

    MakG\UserBundle\Controller\SecurityController:
        class: MakG\UserBundle\Controller\SecurityController
        public: true
        arguments:
            - ~
            - '@security.authentication_utils'

    # Services
    makg_user.avatar_generator.identicon:
        class: MakG\UserBundle\AvatarGenerator\IdenticonGenerator

    makg_user.user_manager:
        class: MakG\UserBundle\Manager\UserManager
        arguments:
            - ~
            - '@doctrine.orm.entity_manager'
            - '@security.password_encoder'

    makg_user.user_manipulator:
        class: MakG\UserBundle\Manager\UserManipulator
        arguments:
            - '@MakG\UserBundle\Manager\UserManagerInterface'
            - '@MakG\UserBundle\AvatarGenerator\AvatarGeneratorInterface'
            - '@filesystem'
            - '@security.csrf.token_generator'

    makg_user.noop_mailer:
        class: MakG\UserBundle\Mailer\NoopMailer

    makg_user.twig_swift_mailer:
        class: MakG\UserBundle\Mailer\TwigSwiftMailer
        arguments:
            - '@mailer'
            - '@twig'
            - ~
            - '@router'

    makg_user.login_manager:
        class: MakG\UserBundle\Security\LoginManager
        arguments:
            - '@security.token_storage'
            - ~

    makg_user.user_checker:
        class: MakG\UserBundle\Security\UserChecker

    makg_user.user_provider:
        class: MakG\UserBundle\Security\UserProvider
        arguments:
            - '@MakG\UserBundle\Manager\UserManagerInterface'

    # Event Subscribers
    makg_user.listener.generate_confirmation_token:
        class: MakG\UserBundle\EventListener\GenerateConfirmationToken
        arguments:
            - '@security.csrf.token_generator'
        tags: [kernel.event_subscriber]

    makg_user.listener.send_emails:
        class: MakG\UserBundle\EventListener\SendEmails
        arguments:
            - '@MakG\UserBundle\Mailer\MailerInterface'
            - '@logger'
        tags: [kernel.event_subscriber]

    # Aliases
    MakG\UserBundle\AvatarGenerator\AvatarGeneratorInterface:
        alias: 'makg_user.avatar_generator.identicon'

    MakG\UserBundle\Mailer\MailerInterface:
        alias: 'makg_user.mailer'

    MakG\UserBundle\Manager\UserManagerInterface:
        alias: 'makg_user.user_manager'

    MakG\UserBundle\Manager\UserManipulatorInterface:
        alias: 'makg_user.user_manipulator'

    MakG\UserBundle\Security\UserChecker:
        alias: 'makg_user.user_checker'
    
